# Generated by Django 3.2.6 on 2021-09-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='tipo',
            field=models.CharField(choices=[('SS', 'Servicio Social'), ('PP', 'Practica Profesional')], max_length=200),
        ),
    ]
