# Generated by Django 3.2.6 on 2021-09-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210924_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('DESACTIVADO', 'Desactivado'), ('ELIMINADO', 'Eliminado')], max_length=200),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('DESACTIVADO', 'Desactivado'), ('ELIMINADO', 'Eliminado')], max_length=200),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.programa'),
        ),
    ]
