# Generated by Django 3.2.6 on 2021-11-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210924_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='matricula',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
